version: '3.8'
name: medicalcenter

networks:
  monitoring:
    driver: bridge
  

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  seq-data:
    driver: local
  sql-data:
    driver: local

services:
  medicalcenters.api:
    image: ${DOCKER_REGISTRY-}medicalcentersapi
    container_name: "Medical_Center_API"
    networks:
      - monitoring
    depends_on:
      - redis
      - sqlserver
      - seq
    environment:
      Otel__Endpoint: http://jaeger:4317
    build:
      context: .
      dockerfile: src/API/MedicalCenters.API/Dockerfile
    ports:
      - "23412:23412"
      - "23413:23413"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - monitoring
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/dаta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - monitoring
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
        - "16686:16686"  
    networks:
      - monitoring
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
    volumes:
      - ./seq-data:/data
    restart: unless-stopped
    networks:
      - monitoring
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123456789!
    volumes:
      - sql-data:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - monitoring
   