<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
    <UserSecretsId>57bde26b-8fb1-429f-9f4e-9c6eb91863fc</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="C#\**" />
    <Content Remove="C#\**" />
    <EmbeddedResource Remove="C#\**" />
    <None Remove="C#\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Program.cs~RF117b23b.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.16.0" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.16.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.16.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.16.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.16.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Process" Version="1.16.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.16.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.16.0-beta.1" />
	  
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="MicroElements.Swashbuckle.FluentValidation" Version="7.1.7" />

	<PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
	<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	<PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
	<PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />

    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\MedicalCenters.Application\MedicalCenters.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\MedicalCenters.Identity\MedicalCenters.Identity.csproj" />
    <ProjectReference Include="..\..\Infrastructure\MedicalCenters.Infrastructure\MedicalCenters.Persistence.csproj" />
  </ItemGroup>

</Project>
